apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pim-backend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/james-rotary/pim-backend-config.git
    targetRevision: development
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: pim-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
